create table jobs (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    payload TEXT not null,
    result TEXT,
    status enum ('FAILED','PENDING','RUNNING','SUCCESS') not null,
    type enum ('EMAIL','REPORT') not null,
    primary key (id)
);
